name: CI-CD-SONARQUBE-TEST # Nombre del workflow

on: # Eventos que activan el workflow
  push:
    branches: # Git push activará el workflow al realizarse en estas ramas
      - main
      - dev
      - feature

env: # Variables de entorno
  SONAR_TOKEN: ${{ secrets.DEV_TOKEN }} # Token para dev branch
  JAVA_SRC: src/com/example/sqlinjectiontest # Directorio del fichero Main.java
  PYTHON_DIR: python # Directorio de los ficheros python
  RESULTS_DIR: results # Directorio de los resultados

jobs: # Conjunto de las tareas
  build-test: # Nombre de la tarea (job)
    runs-on: ubuntu-latest # Virtualiza en Ubuntu

    steps: # Pasos de la tarea
    - name: 📥 Clonar repositorio
      uses: actions/checkout@v4

    # ------------ JAVA BUILD & TEST ------------
    - name: ☕ Congigurando JDK 17... # Instala y configura Java - ZULU
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'zulu'

    - name: 📦 Instalando Checkstyle para Java...
      run: |
        wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.1/checkstyle-10.12.1-all.jar
        wget -O google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.12.1/src/main/resources/google_checks.xml

    - name: 🚀 Ejecutando Checkstyle (Java)...
      run: |
        mkdir -p ${{ env.RESULTS_DIR }}/java
        java -jar checkstyle.jar -c google_checks.xml src/com/example/sqlinjectiontest/Main.java | tee ${{ env.RESULTS_DIR }}/java/checkstyle-output.txt || true
      continue-on-error: true

    - name: 🛠️ Compilando código Java...
      run: |
        javac ${{ env.JAVA_SRC }}/Main.java -d build
      continue-on-error: true

    - name: 📦 Descargando JUnit... # Instala y configura JUnit
      run: |
        wget -O junit-platform-console-standalone-1.10.0.jar \
        https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar

    - name: 🧪 Ejecutando tests unitarios Java (JUnit 5)...
      run: |
        wget -O junit-platform-console-standalone-1.10.0.jar \
        https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar

        java -jar junit-platform-console-standalone-1.10.0.jar \
          --class-path build:tests:junit-platform-console-standalone-1.10.0.jar \
          --scan-class-path | tee ${{ env.RESULTS_DIR }}/java/junit-results.txt
      continue-on-error: true

    - name: 🚀 Ejecutando código Java...
      run: java -cp build com.example.sqlinjectiontest.Main | tee ${{ env.RESULTS_DIR}}/java/java-output.txt || true

    - name: 🧹 Limpiando compilados...
      run: rm -rf build

    # ------------ PYTHON TESTS ------------
    - name: 🐍 Configurando Python... # Instala y configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 📦 Instalando las dependencias para Python... # Instala las librerias de Python a usar
      run: |
        pip install pytest flake8 bandit black requests uuid

    - name: ✏️ Chequeando estilos (flake8)... # Ejecuta flake8
      run: |
        mkdir -p ${{ env.RESULTS_DIR }}/python
        flake8 python/ | tee ${{ env.RESULTS_DIR }}/python/flake-results.txt
      continue-on-error: true
  
    - name: 📊 Chequeando formato (black)... # Ejecuta black
      run: black --check python/ | tee ${{ env.RESULTS_DIR }}/python/black-results.txt
      continue-on-error: true

    - name: 🕵🏻‍♂️ Ejecutando análisis de seguridad (bandit)... # Ejecuta bandit en busca de vulnerabilidades
      run: bandit -r python/ -x tests/ -s B101 | tee ${{ env.RESULTS_DIR }}/python/bandit-results.txt # Ignora el assert de python (-x tests/ -s B101)
      continue-on-error: true

    - name: 🧪 Ejecutando pytests... # Ejecuta los pytests
      run: |
        mkdir -p ${{ env.RESULTS_DIR }}/python
        pytest -s -v --disable-warnings python/file.py | tee ${{ env.RESULTS_DIR }}/python/pytest_file-results.txt
        pytest -s -v --disable-warnings python/test/pixegami_test.py | tee ${{ env.RESULTS_DIR }}/python/pytest_pixegami-results.txt
      continue-on-error: true
      
    # ------------ ARTIFACTS ------------
    - name: 📁 Almanceando resultados... # Almacena los resultados de las pruebas
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results/

    # ------------ SUMMARY ------------
    - name: 📋 Resumen # Resumen de las tareas de Java y Python
      run: |
        echo "✅ Java and Python tasks completed."
        echo "📄 Outputs stored in 'results/' and uploaded as artifacts."

    - name: 📦 Instalando Sonar Scanner...
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        mv sonar-scanner-5.0.1.3006-linux sonar-scanner
        echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

    - name: ☑️ Verificando SonarQube...
      run: |
        curl -I http://rnduk-77-211-5-159.a.free.pinggy.link || true

    - name: 🚀 Ejecutando escaneo de SonarQube...
      run: |
        sonar-scanner \
          -Dsonar.projectKey=VariosTests \
          -Dsonar.host.url=http://rnduk-77-211-5-159.a.free.pinggy.link \
          -Dsonar.token=${{ secrets.DEV_TOKEN }} \
          -Dsonar.sources=python,src \
          -Dsonar.python.version=3.x \
          -Dsonar.qualitygate.wait=true \
          -X
